/**
 * load-test-coordination: Generates 1,000 mock Coordination rows and dispatches
 * them to Supabase via the bulk_import_coordination_tasks RPC.
 *
 * Usage:
 *   npx tsx src/scripts/loadTestCoordination.ts <PROJECT_ID>
 *
 * Requires .env.local to be present with NEXT_PUBLIC_SUPABASE_URL,
 * NEXT_PUBLIC_SUPABASE_ANON_KEY, and TEST_USER_EMAIL / TEST_USER_PASSWORD
 * (see .env.local.example). Authenticates as that dedicated test account.
 */
import { createClient } from '@supabase/supabase-js';
import { randomUUID } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

// Robust local env loading fallback if standard dotenv loading doesn't capture it
if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  try {
    const envPath = path.resolve(process.cwd(), '.env.local');
    if (fs.existsSync(envPath)) {
      const envContent = fs.readFileSync(envPath, 'utf8');
      envContent.split('\n').forEach(line => {
        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
          const key = match[1];
          let value = match[2] || '';
          if (value.startsWith('"') && value.endsWith('"')) {
            value = value.substring(1, value.length - 1);
          } else if (value.startsWith("'") && value.endsWith("'")) {
            value = value.substring(1, value.length - 1);
          }
          process.env[key] = value.trim();
        }
      });
    }
  } catch (e) {
    console.warn('Could not read .env.local file', e);
  }
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const TEST_USER_EMAIL = process.env.TEST_USER_EMAIL!;
const TEST_USER_PASSWORD = process.env.TEST_USER_PASSWORD!;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('❌ Error: Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY in env');
  process.exit(1);
}

if (!TEST_USER_EMAIL || !TEST_USER_PASSWORD) {
  console.error('❌ Error: Missing TEST_USER_EMAIL or TEST_USER_PASSWORD in env (see .env.local.example)');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const MOCK_DISCIPLINES = [
  { id: 'disc-arch',   label: 'Architectural' },
  { id: 'disc-struct', label: 'Structural' },
  { id: 'disc-mep',    label: 'MEP' },
  { id: 'disc-fp',     label: 'Fire Protection' },
  { id: 'disc-civil',  label: 'Civil' },
];

async function main() {
  const projectId = process.argv[2];
  if (!projectId) {
    console.error('Usage: npx tsx src/scripts/loadTestCoordination.ts <PROJECT_ID>');
    process.exit(1);
  }

  console.log(`Authenticating as test user: ${TEST_USER_EMAIL}...`);
  const { error: authError } = await supabase.auth.signInWithPassword({
    email: TEST_USER_EMAIL,
    password: TEST_USER_PASSWORD,
  });

  if (authError) {
    console.error('❌ Authentication failed:', authError.message);
    process.exit(1);
  }
  console.log('✅ Successfully authenticated.');

  console.log(`Querying project_settings disciplines for project ${projectId}...`);
  const { data: projectSettings, error: projectSettingsError } = await supabase
    .from('project_settings')
    .select('disciplines')
    .eq('project_id', projectId)
    .single();

  let disciplines = MOCK_DISCIPLINES;
  if (projectSettingsError) {
    console.warn('⚠️ Could not fetch project settings, using default mock disciplines. Error:', projectSettingsError.message);
  } else if (projectSettings && Array.isArray(projectSettings.disciplines)) {
    disciplines = projectSettings.disciplines;
    console.log(`✅ Loaded ${disciplines.length} disciplines from project settings:`, disciplines.map(d => d.id));
  } else {
    console.warn('⚠️ Disciplines not found in project settings, using defaults.');
  }

  console.log('Generating 1,000 mock coordination tasks...');
  const priorities = ['Critical', 'High', 'Medium', 'Low'];
  const buildingAreas = ['Corridor / Common', 'Unit Interiors', 'Back of House', 'Amenity', 'Parking'];
  const divisions = ['03', '06', '07', '08', '09', '26'];
  const costTypes = ['Labor', 'Material', 'Subcontract', 'Equipment', 'Other'];

  const tasks: any[] = [];
  for (let i = 0; i < 1000; i++) {
    const id = randomUUID();
    const title = `Load Test – Coordination Item #${i + 1}`;
    const description = `Auto-generated by load-test-coordination skill at ${new Date().toISOString()}`;
    const priority = priorities[i % priorities.length];
    const building_area = buildingAreas[i % buildingAreas.length];
    
    const division = divisions[i % divisions.length];
    const randCode = Math.floor(1000 + Math.random() * 9000);
    const cost_code = `${division}${randCode}`;
    
    // Cycle cost types, set null every 6th row
    const cost_type = (i % 6 === 5) ? null : costTypes[i % costTypes.length];

    // Coordination details JSONB
    const coordination_details: Record<string, { status: string; notes: string }> = {};
    disciplines.forEach((disc) => {
      // 50% Pending, 25% Complete, 15% Not Required, 10% Required
      const rand = Math.random();
      let status = 'Pending';
      if (rand < 0.50) {
        status = 'Pending';
      } else if (rand < 0.75) {
        status = 'Complete';
      } else if (rand < 0.90) {
        status = 'Not Required';
      } else {
        status = 'Required';
      }
      coordination_details[disc.id] = { status, notes: '' };
    });

    tasks.push({
      id,
      title,
      description,
      priority,
      building_area,
      cost_code,
      cost_type,
      coordination_details,
      errors: [],
    });
  }

  console.log(`Importing 1,000 tasks in chunks of 100...`);
  const CHUNK_SIZE = 100;
  for (let i = 0; i < tasks.length; i += CHUNK_SIZE) {
    const chunk = tasks.slice(i, i + CHUNK_SIZE);
    const { error } = await supabase.rpc('bulk_import_coordination_tasks', {
      p_project_id: projectId,
      p_payload: chunk,
    });
    if (error) {
      console.error(`❌ Chunk ${Math.floor(i / CHUNK_SIZE) + 1} failed:`, error.message);
      process.exit(1);
    }
    console.log(`✅ Chunk ${Math.floor(i / CHUNK_SIZE) + 1}/${Math.ceil(tasks.length / CHUNK_SIZE)} imported (${chunk.length} rows)`);
  }

  console.log(`\n✅ Load test complete: 1,000 coordination tasks imported to project ${projectId}`);
  console.log(`⚠️  Remember to clean up: DELETE FROM opportunities WHERE title LIKE 'Load Test – %' AND project_id = '${projectId}';`);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
